# Generated by Django 6.1 on 2026-09-02 12:06

import customers.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=customers.models.CustomerEmailField(max_length=100, unique=True),
        ),
    ]
